### ISSUE TITLE
Bad emplementation

### ISSUE THREAD

**Issue by Georgi-Filipov** [stanislaukhamiankou/OnlineStore#10]
![image](https://user-images.githubusercontent.com/90196522/178966499-61fe9fc0-aee2-4e88-85e8-68443765ba46.png)

You've used flex here, but you could use grid instead to minify tsx code.

**Comment by stanislaukhamiankou** [comment]
It will be great to use the layout model later. For now, let's stick with this solution. In the future, you can work on styles. Where appropriate
