### ISSUE TITLE
Why image is able to preview?

### ISSUE THREAD

**Issue by Georgi-Filipov** [stanislaukhamiankou/OnlineStore#11]
![image](https://user-images.githubusercontent.com/90196522/178967075-f896a70e-fb1d-473f-90a8-f910b77a3331.png)
![image](https://user-images.githubusercontent.com/90196522/178967196-35c2de44-ac3a-4daf-b35b-6ba899b09325.png)

This images should be as images without preview

**Comment by stanislaukhamiankou** [comment]
fixed
