### ISSUE TITLE
infinite scroll issue

### ISSUE THREAD

**Issue by Georgi-Filipov** [stanislaukhamiankou/OnlineStore#16]
![image](https://user-images.githubusercontent.com/90196522/178969743-b6298843-1f48-49fa-8e30-b602cb8c42e4.png)

You request without offset and limit. It means you get all data at first time. What is the propose of the infinite scrolling?

**Comment by Georgi-Filipov** [comment]
![image](https://user-images.githubusercontent.com/90196522/178971639-ec704f92-2b44-4918-8ba1-218e9b23fca8.png)

btw you pass this function below. Why don't you use it inside?

**Comment by stanislaukhamiankou** [comment]
fixed
