### ISSUE TITLE
Order issue

### ISSUE THREAD

**Issue by Georgi-Filipov** [stanislaukhamiankou/OnlineStore#5]
![image](https://user-images.githubusercontent.com/90196522/178957870-2c2ca780-3fd2-4c9d-9f49-e02552ed7fc4.png)

1) Why did you use input range here? Is it related to the price?
2) No button to apply or reset filters.
3) When the filters is changed, nothing happens.

**Comment by stanislaukhamiankou** [comment]
Filtering removed. Decided to do a simple search by model name
